### ISSUE TITLE
Deploy the application on Online Server

### ISSUE THREAD

**Issue by SakshayMahna** [CS305-software-Engineering/Service-Request-Application-CS305#10]
To deploy the application for easier evaluation

**Comment by SakshayMahna** [comment]
This involves:

- Integrating SMS API
- Shifting to PostgreSQL for deployment
- Deploying to Heroku

**Comment by acebot712** [comment]
> To deploy the application for easier evaluation

You may postpone this part in favor of getting the working prototype with its main functionality.

**Comment by SakshayMahna** [comment]
https://stone-armor-311114.uc.r.appspot.com/

Application live on this website.

Admin Panel not currently working, requires fixing.

**Comment by Navtej5** [comment]
All working
