### ISSUE TITLE
Next DoA and history

### ISSUE THREAD

**Issue by SakshayMahna** [CS305-software-Engineering/Service-Request-Application-CS305#13]
The functionality and it's related views

**Comment by Navtej5** [comment]
Work done by me and @atul-77 :
- Appointment model added for storing data of all appointments using Foreign key constraint with Request Model.
- Appointment_page created for viewing the pages
- routing for getting to appointment_page from user_page and staff_page
- added functionality of remarks by end-user and service-staff for each appointment
