### ISSUE TITLE
[SRS] Overall Description

### ISSUE THREAD

**Issue by DhamiSamreet** [CS305-software-Engineering/Service-Request-Application-CS305#3]

**Comment by DhamiSamreet** [comment]
Samreet Work Done:
- Software Stack
- Interface Requirments(System features)
- Overall Description and User description
- Workflow(Timeline)

**Comment by Navtej5** [comment]
Work Done:

- Scope of the project
- Page Layouts / UI for different users
- Assumption, Dependencies and Constraints
- User Description
